services:
  - type: web
    name: whatsapp-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn App.api:app -k uvicorn.workers.UvicornWorker --timeout 120
    
  - type: web
    name: chat-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn App.api:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        sync: false
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: USER_EMAIL
        sync: false
      - key: TIMEZONE
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_WEBHOOK_TOKEN
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
